### ISSUE TITLE
예외처리

### ISSUE THREAD

**Issue by yaezzin** [yaezzin/TIL#39]
## 예외처리 

프로그램이 실행 중 어떤 원인에 의해서 오작동을 하거나 비정상적으로 종료되는 경우, 이러한 결과를 초래하는 원인을 ```에러``` 또는 ```오류```라고 한다.

### 발생시점에 따른 분류

* ```컴파일 에러``` : 컴파일 시 발생하는 에러
  * 컴파일러가 소스코드에 대한 오타, 잘못된 구문, 자료형 체크 등에 대한 기본적인 검사루를 수행하여 성공하면 클래스 파일(*.class)가 생성됨
* ```런타임 에러``` : 실행 시에 발행하는 에러
  * 컴파일이 성공하더라도 프로그램 실행시에 에러가 발생하지 않는 것은 아님. 잠재적인 오류가 있을 수 있다.
  * 런타임 에러를 방지하기 위해서는 모든 경우의 수에 대한 대비가 필요하다.
 
### 에러와 예외

* ```에러``` : 프로그램 코드에 의해서 수습될 수 없는 심각한 오류 
  * OutOfMemoryError, StackOverflowError 
* ```예외``` : 적절한 프로그램 코드를 작성하여 프로그램의 비정상적인 종료를 막을 수 있는 오류들
 
## 예외 클래스의 계층 구조

<img width="540" alt="스크린샷 2023-01-16 오후 2 35 11" src="https://user-images.githubusercontent.com/97823928/212605638-5783ab58-6f51-4720-9fd6-6ebf1af7d6cc.png">

* 모든 클래스의 조상은 Object 클래스이므로 Exception곽 Error 클래스 역시 Object 클래스의 자손들!

<img width="440" alt="스크린샷 2023-01-16 오후 2 36 07" src="https://user-images.githubusercontent.com/97823928/212605735-6ab1e394-bcb0-4397-9983-beaaf2b6451b.png">

보통 예외 클래스는 두그룹으로 분류한다.
1. Exception 클래스와 그 자손들
* 주로 외부의 영향으로 발생할 수 있는 것들, 프로그램 사용자들의 동작에 의해서 발생하는 경우가 많음 
2. RuntimeException 클래스와 그 자손들
* 배열의 범위에 벗어난 경우 (ArraryIndexOutOfBoundsException), null 값을 호출하려 한 경우 (NullPointerException), 정수를 0으로 나누려고 하는 경우(ArithmeticException) 등등 ...

**Comment by yaezzin** [comment]
## try - catch문

### 예외처리 (Exception Handling)
프로그램 실행 시 발생할 수 있는 예외에 대한 코드를 작성하여 프로그램의 비정상 종료를 막고 정상적인 실행상태를 유지하기 위해 작성한다.
* 발생한 예외를 처리하지 못하면 프로그램은 비정상적으로 종료되며, ```JVM의 예외처리기```가 받아서 예외의 원인을 화면에 출력한다.

```java
try {
    // 예외가 발생할 가능성이 있는 문장들을 넣음
} catch(Exception e) {
   // 예외 발생 시 이를 처리하기 위한 문장들
} catch(Exception e) {
   // 예외 발생 시 이를 처리하기 위한 문장들
}
```
* 하나의 메서드 내에 여러개의 try-catch 문을 사용할 수 있음
  * 위의 모든 catdh블럭에 참조변수 e 하나만의 사용해도 된다. 
  * 하지만 중첩된 try-catch문의 경우 다른 참조변수 이름을 사용해야 한다.
* 흐름 
  * try 블럭 내에서 예외가 발생하면 발생한 예외와 일치하는 catch블럭을 찾는다. 예외가 발생하지 않는다면 catch블럭을 거치지 않는다.
  * 일치하는 catch 블럭이 있으면 그 블럭 내의 문장들을 수행한다.
  * 일치하는 catch 블럭이 없다면 예외가 처리되지 못한다.
  
```java
try {
    System.out.println(0/0); 
} catch(ArithmeticException e) {

} catch(Exception e) {

}
```
* try 블럭에서 ArithmeticExcpetion이 발생하였고, 첫번째 검사에서 일치하는 catch블럭을 찾았기 때문에 두번째 catch은 찾지 않게 된다.
* 그렇기 때문에 마지막에 Exception 클래스 타입의 참조변수를 선언한 catch문을 사용하면 어떤 종류의 예외가 발생하더라도 이 블럭에 의해서 처리될 수 있다.

**Comment by yaezzin** [comment]
## printStackTrace()란

예외가 발생했을 때 생성되는 예외 클래스의 인스턴스에는 발생한 예외에 대한 정보가 담겨져 있다.
이러한 정보들은 ```getMessage()```와 ```printStackTrace()```를 통해 얻을 수 있다.

```java
class ExceptionEx { 
    ... 생략
    try {
        System.out.println(0/0); 
    } catch(ArithmeticException e) {
        e.printStackTrace();
       System.out.println("예외 메세지 : " + e.getMessage());
    }
}
```

#### 실행결과
```java
java.lang.ArithmeticException: / by zero at ExceptionEx.main(ExceptionEx.java:3)
예외 메세지 : /by zero
```

* printStackTrace()를 사용해서 호출스택에 대한 정보와 예외 메세지를 출력할 수 있다.
* 에러의 발생근원지부터 ```단계별```로 출력

## 지양하는 이유 ?
* printStackTrace()를 사용하게 되면 패키지, 클래스 및 오류의 종류까지 전부 출력을 하게 된다.
  * 공격자는 해당 로그를 탈취하여 각종 클래스 및 정보를 획득할 수 있으며, 내부 구조를 쉽게 파악할 수 있다.
  * 그러므로 개발 서버에서는 사용해도 되나 운영서버로 코드를 배포할 때는 예외를 log로 처리하는 것이 좋다.
* JAVA의 Reflection을 이용하여 예외를 추적하는 것이라 많은 오버헤드가 발생할 수 있다.
* 메서드 스택정보를 취합하기 때문에 서버 부하의 원인이기도 하다.
* 내부적으로 System.err을 사용하는데 비용이 비싼편이다. 

## 출처
* [Spring - e.printStackTrace() 보다 StackTraceElement로 로깅하기](https://kim-jong-hyun.tistory.com/112#:~:text=%EA%B7%B8%EB%9F%AC%EB%82%98%20e.printStackTrace()%EB%8A%94,%EB%B6%80%ED%95%98%EC%9D%98%20%EC%9B%90%EC%9D%B8%EC%9D%B4%EA%B8%B0%EB%8F%84%20%ED%95%98%EB%8B%A4.)

**Comment by yaezzin** [comment]
# throw와 throws
## throw

키워드 ```throw```를 사용하면 프로그래머가 **고의로 예외를 발생**시킬 수 있다.
```java
1. new를 통해 발생시키려는 예외클래스의 객체를 만든다.
    Exception e = new Excpetion("고의로 발생시킴");
2. throw를 통해서 예외를 발생시킴
    throw e;
3. throw new Exception("고의로 발생시킴"); 처럼 한 줄로 줄여 쓸 수 있다.
```

## throws

throws를 사용해서 자신을 호출한 상위 메소드로 에러를 던질 수 있다.

```java
void method() throws Exception {
    // 메서드 내용
}
```
* 메서드의 ```선언부에 에외를 선언```함으로써 메서드 사용자가 선언부를 보았을 때 어떠한 예외들이 처리되어야 하는지 쉽게 파악할 수 있다.
* 메서드에 예외를 선언할 때 일반적으로 RuntimeException 클래스들은 적지 않는다. (unchecked 에러이기 떄문에 문제가 되지 않는다)
* 그러므로 반드시 처리되어야 하는 예외들만 선언해주는 것이 좋다.

앞서 ```throws를 사용해서 자신을 호출한 상위 메소드로 에러를 던질 수 있다```라고 하였는데,

```java
class ExceptionEx12 {
	public static void main(String[] args) throws Exception {
		method1(); // 같은 클래스내의 static멤버이므로 객체생성없이 직접 호출가능.
  	}

	static void method1() throws Exception {
		method2();
	}	

	static void method2() throws Exception {
		throw new Exception();
	}	
}

출력값
Exception in thread "main" java.lang.Exception
        at ExceptionEx12.method2(ExceptionEx12.java:11)
        at ExceptionEx12.method1(ExceptionEx12.java:7)
        at ExceptionEx12.main(ExceptionEx12.java:3)
```
*  이러한 식으로 계속 호출스택에 있는 메서드들을 따라 전달되다가 제일 마지막에 있는 main 메서드에서도 예외처리가 되지 않으면 main 메서드마저 종료되어 프로그램이 전체 종료된다.
* 이것으로 예외가 처리된 것이 아니라 단순히 예외를 전달만 한 것이기 때문에 어느 한 곳에서 try-catch문으로 예외처리를 해주어야 한다.

### 방법1 

```java
public static void main(String[] args) {
    method1(); 
 }

static void method1() {
    try {
        throw new Exception(); // 고의로 예외 발생
    } catch (Exception e) {
        e.printStackTrace();
    }
}	
```

### 방법2

```java
public static void main(String[] args) {
    try {    
        method1(); 
    } catch (Exception e) {
        e.printStackTrace();
    }
}

static void method1() throws Exception {
    throw new Exception(); // 고의로 예외 발생
}	
```

### 차이 ?

방법 1은 메서드 1에서 예외처리를 한 반면, 방법 2는 method1에서 예외를 선언하여 자신을 호출하는 main메서드에서 예외처리를 했다.
분명 어디서든 예외처리를 하면되는데 무슨 차이가 있을까?

먼저, 방법1의 경우에는 메서드 내에서 예외가 처리되어지면 메서드1을 호출한 메서드는 예외가 발생했다는 사실 조차 모르게 된다.
하지만 방법2처럼 호출한 메서드로 넘겨주면 메서드를 호출한 라인에서 예외가 발생한 것으로 간주된다.

**Comment by yaezzin** [comment]
## try-with-resources

try-with-resources문은 try에 자원 객체를 전달하면, try 코드 블록이 끝나면 자동으로 자원을 종료해주는 기능이다.
즉, 따로 finally 블록이나 모든 catch 블록에 종료 처리를 하지 않아도 된다.

```java
try (SomeResource resource = getResource()) {
    use(resource);
} catch(...) {
    ...
}
```
* 괄호 안에 객체를 생성하는 문장을 넣으면 따로 close()를 호출하지 않더라도 try문을 벗어나는 순간 자동적으로 close()가 호출된다.

하지만 자동으로 close()가 호출될 수 있으려면, 클래스가 ```AutoCloseable 인터페이스```를 구현한 것이어야만 한다.
```java
public interface AutoCloseable {
    void close() throws Exception;
}
```

## 자원반납 순서

자원 반납 순서의 경우 **나중에 선언된** 리소스부터 close(반납) 됩니다.

```java
public class CustomResource1 implements AutoCloseable {
 
    public CustomResource1() {
        System.out.println("CustomResource Constructor_1");
    }
 
    public void printMessage() {
        System.out.println("CustomResource Print Message_1");
    }
 
    @Override
    public void close() throws Exception {
        System.out.println("CustomResource close_1");
 
    }
}

public class CustomResource2 implements AutoCloseable {
 
    public CustomResource2() {
        System.out.println("CustomResource Constructor_2");
    }
 
    public void printMessage() {
        System.out.println("CustomResource Print Message_2");
    }
 
    @Override
    public void close() throws Exception {
        System.out.println("CustomResource close_2");
 
    }
}

public class ResourceClose {
    public static void main(String[] args) {
        try (CustomResource1 cr1 = new CustomResource1(); CustomResource2 cr2 = new CustomResource2()) {
            cr1.printMessage();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
#### 결과
```
CustomResource Constructor_1
CustomResource Constructor_2
CustomResource Print Message_1
CustomResource close_2
CustomResource close_1
```

ResourceClose 클래스는CustomResource1, CustomResource2 이렇게 2개의 리소스를 순서대로 생성하였다. 하지만 결과를 보면
* 리소스 생성은 CustomResource1, CustomResource2 순서로 되었지만,
* 리소스 자원 반납(close)는 CustomResource2, CustomResource1 순서로 된 것을 볼 수 있다.

## 출처
* [[Java] Try with resources 로 자원 반납하기](https://hianna.tistory.com/546)

**Comment by yaezzin** [comment]
## 사용자 정의 예외

기존에 정의된 예외 클래스 외에 필요에 따라 프로그래머가 새로운 예외 클래스를 정의할하여 사용할 수 있다.
* 보통은 Exception클래스 또는 RuntimeException클래스로부터 상속받아 클래스를 만든다.

```java
class MyException extends Exception {
	// 에러 코드 값을 저장하기 위한 필드를 추가했다.
    private final int ERR_CODE; // 생성자를 통해서 초기화 한다.
    
    MyException(String msg, int errCode) { // 생성자
    	super(msg);
        ERR_CODE = errCode;
	}

	MyException(String msg) { // 생성자
		this(msg, 100) // ERR_CODE를 100(기본값)으로 초기화한다.
	}
	public int getErrCode() { // 에러 코드를 얻을 수 있는 메서드도 추가했다.
    	return ERR_CODE; // 이 메서드는 주로 getMessage()와 함께 사용될 것이다.
    }
} 
```
기존의 예외 클래스의 경우 주로 Exception 클래스를 상속받아서 checked 예외로 작성하는 경우가 많았지만,
요즘은 예외처리를 선택적으로 하기 위해 RuntimeException클래스를 상속받아서 작성하는 쪽으로 바뀌어가고 있다.
* checked 예외는 반드시 예외처리를 해주어야 하므로 예외처리가 불필요한 경우에도 try-catch문을 넣어 코드가 복잡해지기 때문이다.
